version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: laraec
          - DB_CONNECTION: mysql
          - DB_DATABASE: laravel
          - DB_USERNAME: root
 
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: laravel
 
    steps:
      - checkout
 
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "htdocs/composer.json" }}
            - v1-dependencies-
 
      - run: 
          working_directory: htdocs
          command: composer install -n --prefer-dist
 
      - save_cache:
          key: v1-dependencies-{{ checksum "htdocs/composer.json" }}
          paths:
            - ./vendor
 
      - run: 
          working_directory: htdocs
          command: echo "APP_KEY=" > .env.circleci
      - run: 
          working_directory: htdocs
          command: php artisan key:generate
      - run: 
          working_directory: htdocs
          command: php artisan migrate:refresh --seed --env=circleci
 
      - run: 
          working_directory: htdocs
          command: vendor/bin/phpunit
