version: '3'

services:

  apache:
    image: laravel-study/apache
    container_name: laravel-study-apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../htdocs:/var/www/html

  php:
    image: laravel-study/php
    container_name: laravel-study-php
    build:
      context: "./php"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
     - ./php/logs:/var/log/php
     - ../htdocs:/var/www/html

  mysql:
    image: laravel-study/mysql
    container_name: laravel-study-mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql

  phpmyadmin:
    image: laravel-study/phpmyadmin
    container_name: laravel-study-phpmyadmin
    build:
      context: "./phpmyadmin"
      dockerfile: "Dockerfile"
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
      - "./phpmyadmin/sessions:/sessions"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel-study-mailhog
    ports:
      - 8025:8025
      - 25:1025

  s3:
    image: minio/minio:latest
    container_name: laravel-study-s3
    environment:
      MINIO_ACCESS_KEY: "access_key"
      MINIO_SECRET_KEY: "secret_key"
    ports:
      - 9090:9000 # VSCodeと競合するので9090番ポートを指定
    command: ["--compat", "server", "/data"]
    volumes:
      - ./s3/data:/data
